# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-opengl}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrea Fazzi"]
  s.date = %q{2009-04-05}
  s.description = %q{ffi-opengl is an autogenerated[1] ruby FFI interface towards OpenGL libraries (GL, GLU, GLUT). The FFI layer ensures compatibility among all Ruby implementation that support it. At the moment, this means that you can run the same ffi-opengl script with MRI Ruby and JRuby.  ffi-opengl API aims to be a 1:1 tranposition of the OpenGL C API: don't expect idiomatic ruby inside!}
  s.email = %q{andrea.fazzi@alcacoop.it}
  s.extra_rdoc_files = ["History.txt", "README.rdoc"]
  s.files = [".gitignore", "History.txt", "README.rdoc", "Rakefile", "bench/bench_spinning_cube.rb", "bench/ffi-opengl_spinning_cube.rb", "bench/ruby-opengl_spinning_cube.rb", "examples/gears.rb", "examples/spinning_cube.rb", "ffi-opengl.gemspec", "generated/gl_wrap.rb", "generated/gl_wrap.xml", "generated/glu_wrap.rb", "generated/glu_wrap.xml", "generated/glut_wrap.rb", "generated/glut_wrap.xml", "interfaces/freeglut_std.h", "interfaces/gl.h", "interfaces/gl.i", "interfaces/glu.h", "interfaces/glu.i", "interfaces/glut.i", "lib/ffi-opengl.rb", "lib/ffi-opengl/gl.rb", "lib/ffi-opengl/glu.rb", "lib/ffi-opengl/glut.rb", "lib/ffi-opengl/platform.rb", "spec/ffi-opengl_spec.rb", "spec/spec_helper.rb", "tasks/ann.rake", "tasks/bones.rake", "tasks/gem.rake", "tasks/generator.rake", "tasks/git.rake", "tasks/notes.rake", "tasks/post_load.rake", "tasks/rdoc.rake", "tasks/rubyforge.rake", "tasks/setup.rb", "tasks/spec.rake", "tasks/svn.rake", "tasks/test.rake"]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/remogatto/ffi-opengl}
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{ffi-opengl}
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{ffi-opengl is an autogenerated[1] ruby FFI interface towards OpenGL libraries (GL, GLU, GLUT)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 0.3.0"])
    else
      s.add_dependency(%q<ffi>, [">= 0.3.0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 0.3.0"])
  end
end
